export default {
    SUCCESS: "SUCCESS",
    FAILURE: "FAILURE",
    REQUEST: "REQUEST",
    SET_TYPE: "SET_TYPE",
    SET_LOCATION: "SET_LOCATION",
    SET_NAME: "SET_NAME",
    REMOVE_ERROR: "REMOVE_ERROR",
    SET_ERROR: "SET_ERROR",
    SUCCESS_GET_PROFESSORS: "SUCCESS_GET_PROFESSORS",
    FAILURE_GET_PROFESSORS: "FAILURE_GET_PROFESSORS",
    REQUEST_GET_PROFESSORS: "REQUEST_GET_PROFESSORS"
};